ABBREVIATIONS = [[r"i'm", "i am"],
                 [r"he's", "he is"],
                 [r"she's", "she is"],
                 [r"that's", "that is"],
                 [r"what's", "what is"],
                 [r"where's", "where is"],
                 [r"\'ll", " will"],
                 [r"\'ve", " have"],
                 [r"\'re", " are"],
                 [r"\'d", " would"],
                 [r"\'ve", " have"],
                 [r"won't", "will not"],
                 [r"don't", "do not"],
                 [r"did't", "did not"],
                 [r"can't", "can not"],
                 [r"it's", "it is"],
                 [r"couldn't", "could not"],
                 [r"have't", "have not"]]
